### ISSUE TITLE
Image placeholders in demo don't load

### ISSUE THREAD

**Issue by strarsis** [juanbrujo/js-background-blend-mode#1]
In [demo](https://codepen.io/juanbrujo/full/DnghH) linked in readme the placeholder images don't seem to load.

**Comment by juanbrujo** [comment]
I'm having no problem

![screen shot 2018-09-26 at 8 49 50 pm](https://user-images.githubusercontent.com/362186/46115538-cf967280-c1cd-11e8-8a08-a31ac0391c40.png)

**Comment by strarsis** [comment]
@juanbrujo: 
I rechecked, the sample image from lorempixel doesn't load for me (Chrome on Windows 10), timeout:
http://lorempixel.com/400/200/
Edit: Apparently it loads sometimes after a very long time for me.

**Comment by juanbrujo** [comment]
Yes, it is taking a while. I changed the protocol from `http` to `https` and it seems to be improved.
